### ISSUE TITLE
usercontroller 작성

### ISSUE THREAD

**Issue by tmdqls2257** [tmdqls2257/NextNestBlog-Server#3]
### ISSUE
  * Detail:  user controller를 만들어 로직 구현하기

### TODO
- [x]  로그인 로직 구현
- [x]  로그아웃 로직 구현
- [x]  회원가입 로직 구현
- [x]  유저 정보 가져오는 로직 구현

### CODE
```tsx

@Controller("users")
export class UsersController {
  private readonly logger = new Logger(UsersController.name);

  constructor(
    private readonly usersService: UsersService,
    @InjectRepository(UserEntity)
    private readonly usersRepository: Repository<UserEntity>
  ) {}

  @ApiOperation({ summary: "모든 유저 정보 가져오기" })
  @Get()
  @UseGuards(JwtAuthGuard)
  @UseInterceptors(OnlyPrivateInterceptor)
  async getCurrentUser(@CurrentUser() currentUser: UserDTO) {
    return currentUser;
  }

  @ApiOperation({ summary: "회원가입" })
  @Post()
  async signUp(@Body() userRegisterDTO: UserRegisterDTO) {
    return await this.usersService.registerUser(userRegisterDTO);
  }

  @ApiOperation({ summary: "로그인" })
  @Post("login")
  async logIn(
    @Body() userLoginDTO: UserLogInDTO,
    @Res({ passthrough: true }) response: Response
  ) {
    // user의 정보와 jwt를 분리하여 jwt는 cookie에 넣어줍니다.
    const { jwt, user } = await this.usersService.verifyUserAndSignJwt(
      userLoginDTO.email,
      userLoginDTO.password
    );

    response.cookie("jwt", jwt, {
      maxAge: Number(process.env.TOKEN_EXPIRESIN) * 1000,
      httpOnly: true,
      sameSite: "none",
      secure: true,
    });
    return user;
  }

  @ApiOperation({ summary: "로그아웃" })
  @Post("logout")
  async logOut(@Res({ passthrough: true }) response: Response) {
    response.clearCookie("jwt");
    // return response.status(200).json({ message: 'User has been logout' });
  }
}

```
